jobs:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      script:
        - cd ui
        - npm ci
        - npm run build
        - cd ../app
        - npm ci
        - npm run tsc
        - npm run electron:build -- -m --publish onTagOrDraft

    - os: linux
      services: docker
      language: generic
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
      script:
        - |
          docker run --rm \
          --env GH_TOKEN=$GH_TOKEN \
          -v ${PWD}:/project \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine \
          /bin/bash -c " \
            cd ui && \
            npm ci && \
            npm run build && \
            cd ../app && \
            npm ci && \
            npm run tsc && \
            npm run electron:build -- -lw --publish onTagOrDraft \
          "

cache:
  directories:
    - app/node_modules
    - ui/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
